
server:
  port: 18000

spring:
  application:
    name: stats-service
  profiles:
    active: dev
  # MySQL-Server & JPA 설정
  # Quarkus 기반 Keycloak-Server 을 이용한 인증 처리
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/inkcloud
          # jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          jwk-set-uri: http://localhost:8080/realms/inkcloud/protocol/openid-connect/certs
#   datasource:   
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/stats_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
#     username: root
#     password: 1234  
#     hikari:
#       connection-timeout: 20000
#       maximum-pool-size: 10
#       initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:  
        "[format_sql]": true
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.inkcloud.review_service.dto,com.inkcloud.product_service.dto"



# 로깅 설정
logging:  
  level:
    root: info
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.mzc.review_service: INFO

# Eureka-Server 에 자가 등록 설정
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    prefer-ip-address: true
  client:  
    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
